Add the stringResult option
CruGlobal/ab-utils pull request #61
Opened 2023-11-02 08:32 UTC by guyyoo

## Release Notes

- Add the stringResult option.
- https://github.com/digi-serve/ab_service_api_sails/issues/113

2023-11-02 08:38 UTC, nh758 requested changes
Looks good but could you add a unit test to cover this?
Also run `npm run docs` to update the documentation.

2023-11-02 08:38 UTC, nh758 commented on utils/serviceRequest.js
> +    * @param {number}[options.stringResult=false] Return the results as a string data type.
should it be boolean?

2023-11-02 09:02 UTC, wongpratan approved these changes

2023-11-03 02:26 UTC, nh758 approved these changes
Great, thanks!

2023-11-03 02:42 UTC, merged